### ISSUE TITLE
Running problem

### ISSUE THREAD

**Issue by p178899** [mattwright324/youtube-metadata#10]
Hi Matt
i have installed your script here:
https://www.videocorsogratis.it/prova/index.html

i added my youtube api key in youtube-api-v3.js and youtube-metadata.js .. but something goes wrong ("There was a problem querying for the video"). Can you help me please?

**Comment by mattwright324** [comment]
In the browser console you have a quota error. I haven't added a custom quota message yet to this app so have to check the console for it.
![image](https://user-images.githubusercontent.com/7717432/104729407-60c6e580-5706-11eb-965a-ac3f7b6b7af3.png)

See here for more detail and assume the issue is likely related to the `10,000 unit` quota for new projects.
https://github.com/mattwright324/youtube-geofind/issues/11

**Comment by p178899** [comment]
This page (https://www.videocorsogratis.it/prova/index.html) is only for testing, cannot be a quota error.
Anyway i have created a new api key and updated js scripts ... but the result is the same :-(

**Comment by mattwright324** [comment]
How much quota is on the project?

https://console.developers.google.com/

Select your project from the navigation -> Dashboard -> YouTube Data API v3 -> Quotas

**Comment by p178899** [comment]
![quotas](https://user-images.githubusercontent.com/49979312/104917213-66852b00-5993-11eb-81d5-0c752d9b1477.jpg)

**Comment by mattwright324** [comment]
Not there, one page back in the Dev Console, can't see it in the Cloud Console. Expand the first Queries section and you should see something like this...

![image](https://user-images.githubusercontent.com/7717432/104918310-8e0fcf80-5962-11eb-884d-69f3cadbed58.png)

I'm thinking you might have a case of this, another project I created but is 'inactive' so the quota got reduced to 0. I haven't looked much into this situation but you might just have to create a new project.

![image](https://user-images.githubusercontent.com/7717432/104918400-b13a7f00-5962-11eb-9921-fc07453a0ce6.png)

**Comment by p178899** [comment]
These are my cloud e dev console, as you can see for my project quotas data are available in cloud console only.

As you suggest i have created a new project because the last was very old and could be inactive.
But i got the same error ... :-(
Thank you for your patience.

![cloud](https://user-images.githubusercontent.com/49979312/105012083-09927f00-5a3e-11eb-9a0b-8a4c4f92cb38.jpg)

![dev](https://user-images.githubusercontent.com/49979312/105012112-0f886000-5a3e-11eb-9d9a-0fd277d9e2c3.jpg)

**Comment by p178899** [comment]
Today everything is ok!
The new project needed a few hours to run correctly.

Thank you for your great script.
