### ISSUE TITLE
Hello, please do not use cors.eu.org directly for large requests

### ISSUE THREAD

**Issue by netnr** [mattwright324/youtube-metadata#100]

**Comment by mattwright324** [comment]
Apologies, I assume my bulk thumbnail export feature is at fault. There can be potentially thousands of images it will try to fetch when checking the option to do so. I can look into creating my own instance of a cors-anywhere proxy so that I'm not causing your service any issues.

**Comment by mattwright324** [comment]
I've created my own instance `https://cors-proxy-mw324.herokuapp.com`, whitelisted my domain, and swapped out usages of `cors.eu.org`.
