### ISSUE TITLE
add a link to a timezone converter for video upload date

### ISSUE THREAD

**Issue by fenopa** [mattwright324/youtube-metadata#123]
I was using this for this purpose: https://citizenevidence.amnestyusa.org/
But they are broken for a while

I think it was using a link like this: https://www.timeanddate.com/worldclock/converter.html?iso=20220805T220000

Can you add a link for video upload dates to see it on different timezones? Reason for asking is YouTube shows dates in your local timezone and that sometimes differs by 1 day from their original upload location. It's nice to check when it was actually uploaded.

**Comment by mattwright324** [comment]
Hi @fenopa 

As far as I know the video publish date returned from the YouTube API is always GMT +00:00 and not your local timezone. I wouldn't mind adding a link or way to transform that to alternative timezones though, I can look into this.

**Comment by mattwright324** [comment]
However, it appears that the reason amnesty's is broken is because they hit the quota limit when checking the browser console. Their site should be back to normal after midnight PST.

![image](https://user-images.githubusercontent.com/7717432/183225215-875c5b07-50dc-4c7b-a5de-a3fd08439c39.png)

**Comment by fenopa** [comment]
> Hi @fenopa
> 
> As far as I know the video publish date returned from the YouTube API is always GMT +00:00 and not your local timezone. I wouldn't mind adding a link or way to transform that to alternative timezones though, I can look into this.

Thanks for response, yes API returns GMT +0 I guess but when you view a youtube link in browser, you get local timezone which is sometimes problematic because it can differ from actual original upload day. That's why I was using that amnesty's tool but your tool is so much more awesome with regards to details. It would be so nice to add a similar link or a way to transform video publish date.

Their tool is broken for months btw.

Thanks for consideration.

**Comment by fenopa** [comment]
Hi, is there any update on this?

**Comment by mattwright324** [comment]
Hey @fenopa,

Sorry, when I was looking at timeanddate.com that you linked the `iso` parameter at the end didn't seem to work really. I was looking for alternative sites that would work though didn't find any I liked. Other things took my focus but I can try to solve this again, potentially with a custom solution.

**Comment by mattwright324** [comment]
Just pushed changes for this, you will now see `(convert)` on dates on the Normal page.

**Comment by fenopa** [comment]
> Just pushed changes for this, you will now see `(convert)` on dates on the Normal page.

Hi, thanks a lot, I'm using it and it works great. Thanks again for considering!

**Comment by fenopa** [comment]
@mattwright324 I noticed a problem with these convert links on a different computer. The problem is, it makes convert links by adding the local time zone to it. I mean, if the local timezone of the computer is GMT+2, it will make the link let's say for a 20:00 date as 22:00. I noticed this now because local timezone of my main computer was GMT+0 so it wouldn't make that change on that computer but I noticed it makes a wrong link with local timezone.
Can you make it so it wouldn't make such adjustment and send only the metadata time?

**Comment by mattwright324** [comment]
This does appear to be an issue but it should be an easy fix. I didn't realize it would convert the utc timestamp to local but all I need to do is add `.utc()` to set it back before using it for the convert link.

**Comment by fenopa** [comment]
@mattwright324 thank you, looking forward for the fix, cheers.

**Comment by mattwright324** [comment]
This is now fixed
