### ISSUE TITLE
Quota Exceeded

### ISSUE THREAD

**Issue by PlutoDoma00** [mattwright324/youtube-metadata#126]
I read https://github.com/mattwright324/youtube-geofind/issues/11 and wait for days, however I still get the "See more detail here with issue #3." Whether its a channel, user, or video, same result. What did I miss?

**Comment by mattwright324** [comment]
I believe someone has been automating usage of my application for quite a while and that is using up the quota each day. There is only so much I can do to prevent it

**Comment by PlutoDoma00** [comment]
> I believe someone has been automating usage of my application for quite a while and that is using up the quota each day. There is only so much I can do to prevent it

So that's the problem. ......Any alternative recommendation you know of?
