### ISSUE TITLE
Everything is good, but some data is wrong on your website.

### ISSUE THREAD

**Issue by wayne931121** [mattwright324/youtube-metadata#134]
I see it on you website:
```
https://mattw.io/youtube-metadata/

Localizations for...
ZH-TW which is Chinese / Taiwan (Province of China)
```
I am a Taiwanese, Taiwan is a country, don't get entangled in the literal meaning.  But if you say it correctly on your website, the China government will make your website banned in China, unless their nationals use a VPN.

Taiwan is not a province of China.

China people may say that Taiwan is a province of China, which is normal, because they cannot surf the Internet normally and must use a VPN(Also see: https://surfshark.com/blog/vpn-in-china).

**Comment by mattwright324** [comment]
Hi @wayne931121 

Apologies. The country code translations in the app are copied directly from Wikipedia for the ISO 3166 standard with whatever wording is used by the standard. 

https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
https://github.com/mattwright324/youtube-metadata/blob/master/js/iso-3166-translator.js

**Comment by wayne931121** [comment]
> Hi @wayne931121
> 
> Apologies. The country code translations in the app are copied directly from Wikipedia for the ISO 3166 standard with whatever wording is used by the standard.
> 
> https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes https://github.com/mattwright324/youtube-metadata/blob/master/js/iso-3166-translator.js

I see, that is true, the country code in iso-3166 for tw is Taiwan (Province of China), and Taiwan is a country in Wikipedia.

https://wikipedia.org/wiki/Taiwan

https://www.iso.org/obp/ui/#iso:code:3166:TW
