### ISSUE TITLE
Youtube Video Category

### ISSUE THREAD

**Issue by wayne931121** [mattwright324/youtube-metadata#135]
I notice you website have no video category. If you have time or want to improve your website, you can add it.
![Screenshot_20230209-204222](https://user-images.githubusercontent.com/75261164/217816341-a49448fc-4c27-4e25-bec1-fb46c9129588.jpg)
In this picture:
```python
"categoryId": "27"
```
It is meaning Education.

Here is categoryId list:
https://gist.github.com/dgp/1b24bf2961521bd75d6c
```
2 - Autos & Vehicles
1 -  Film & Animation
10 - Music
15 - Pets & Animals
17 - Sports
18 - Short Movies
19 - Travel & Events
20 - Gaming
21 - Videoblogging
22 - People & Blogs
23 - Comedy
24 - Entertainment
25 - News & Politics
26 - Howto & Style
27 - Education
28 - Science & Technology
29 - Nonprofits & Activism
30 - Movies
31 - Anime/Animation
32 - Action/Adventure
33 - Classics
34 - Comedy
35 - Documentary
36 - Drama
37 - Family
38 - Foreign
39 - Horror
40 - Sci-Fi/Fantasy
41 - Thriller
42 - Shorts
43 - Shows
44 - Trailers
```
The category is set by video author, use youtube studio:
![Screenshot_20230209-205337](https://user-images.githubusercontent.com/75261164/217818354-7a525b05-324a-40ec-8281-eae2cc20392b.jpg)

![Screenshot_20230209-205346](https://user-images.githubusercontent.com/75261164/217818377-3aa0d873-9abf-4fa8-80c0-75ea37379b68.jpg)

**Comment by mattwright324** [comment]
Good idea, I will look into adding this

**Comment by mattwright324** [comment]
This has been added and will now display what the categoryId means below the snippet section.
