### ISSUE TITLE
"other resources" suggestion

### ISSUE THREAD

**Issue by fenopa** [mattwright324/youtube-metadata#138]
you list some resources like archive.org, filmot, ghostarchive etc. under "Check other resources for details or archival"

Can I suggest this also? https://www.youtuberecover.com/

Sometimes it can bring you an archived metadata where other options fail.

It can be linked like this: `https://www.youtuberecover.com/watch?v=videoID
`
and for channels, like this: `https://www.youtuberecover.com/channel?id=channelID`

thanks for consideration.

**Comment by mattwright324** [comment]
Hi @fenopa 

I had thought youtube recover went offline but that must have been only for a short period. I can definitely add it!

https://web.archive.org/web/20210303211211/https://youtuberecover.com/

**Comment by fenopa** [comment]
Thank you

**Comment by mattwright324** [comment]
Link is now available
