### ISSUE TITLE
pulling filmot data on available/unlisted videos

### ISSUE THREAD

**Issue by aJ2d2O8I** [mattwright324/youtube-metadata#158]
maybe a button that says "Show old metadata"
once filmot archives a video, it never updates the json, so the title/description of it (or even the channel title) remain the same forever

**Comment by mattwright324** [comment]
Filmot has cloudflare protection in place now so any queries I had previously would not function. I provide a prefilled link to Filmot for still available/unlisted videos but I didn't query for them because I don't want his service to be unnecessarily queried.
