### ISSUE TITLE
Grayscale preview is no longer grayscale

### ISSUE THREAD

**Issue by arilotter** [mattwright324/youtube-metadata#174]
> Greyscale preview
> 
> A video where the preview is in greyscale, 
when hovering the mouse over the time bar.
> 
>     https://youtu.be/75d4UgvPHQI

This video now has a Grayscale thumbnail, but the timeline preview is now in color
![test](https://github.com/mattwright324/youtube-metadata/assets/666465/22bdcf8c-8254-44f4-92ba-06de01129369)
![image](https://github.com/mattwright324/youtube-metadata/assets/666465/bc12b828-0296-45eb-b264-5ee387f4efd1)

**Comment by mattwright324** [comment]
Interesting, I'll update that listed case in the wiki thanks!

**Comment by mattwright324** [comment]
Updated
