### ISSUE TITLE
Is it not possible to get the legacy username url?

### ISSUE THREAD

**Issue by jenlunds** [mattwright324/youtube-metadata#176]
Legacy username url _youtube.com/user/_

Do you know when YT stopped doing the username url?

**Comment by codex1001** [comment]
No, it's not possible. It was announced that the new url layout (@handle) will be switched on [10 Oct 2022](https://support.google.com/youtube/thread/183284252/%F0%9F%93%A3-announcing-youtube-handles-a-unique-identifier-to-discover-and-connect-on-youtube).
As of November 14, 2022, the following URL purchases have been removed.
  /user
/c
/directusername

**Comment by mattwright324** [comment]
Codex is right that there is no easy way to get someone's legacy /user/ anymore. The only thing that comes back in the official API are the newer custom channel @'s. The username url still exists and is usable for old accounts that have one, but its legacy and you can't change it. As for when it became legacy, I can't find a solid date but see references to it as being legacy at least >10 years ago.

The only way to get that legacy url would be to manually search the internet & archive.org and hope that it was archived or shared somewhere.

https://support.google.com/youtube/answer/6180214?hl=en
