### ISSUE TITLE
Great Job, but...

### ISSUE THREAD

**Issue by ludyyuan** [mattwright324/youtube-metadata#177]
Thank you for developing such a useful tool.

But I found that when a channel has a large number of videos, e.g. 100000+, this tool can only list about 20,000 records.

Is there any solution?

**Comment by mattwright324** [comment]
Hi @ludyyuan 

Thanks! Unfortunately the 20,000 videos from an uploads playlist is an API limitation on the `playlistItems.list` as set by Google so there isn't really anything I can do about that. Outside the channel uploads playlist, standard playlists can also only have a maximum of 5,000 videos in them
