### ISSUE TITLE
I created a dark mode

### ISSUE THREAD

**Issue by joern19** [mattwright324/youtube-metadata#31]
I have played around with the css and created a simple dark mode.
Tell me if you like / what you think of it and I will tidy up the code and create a pull request.
![Untitled](https://user-images.githubusercontent.com/42153526/129445140-6190b65d-f996-4f1e-a624-2251f9cc4a34.png)

**Comment by mattwright324** [comment]
Hey @joern19,

Certainly is a cool idea! My main concern with the dark mode as you have it would be tweaking the contrast of colors (links, titles, text highlights) besides the standard text. A solid color background is probably fine though I'm curious how a color inverted version of the current repeating background image might look.

I am using [highlightjs](https://highlightjs.org/) for the response code blocks, its has a variety of available styles including some dark mode ones that may be better suited for this too.

**Comment by mattwright324** [comment]
I am currently updating the UI to be dark-mode default and provide a switch to go back to light. I am switching the project from `fomantic-ui` to `Bootstrap 5.1` which exists a [handy library to switch between light/dark](https://vinorodrigues.github.io/bootstrap-dark-5/).

- Metadata Normal
  - highlightjs will swap between `stackoverflow-dark` and `stackoverflow-light`
- Metadata Bulk
  - DataTables using bootstrap 5 style which changes colors based on the theme switching library
  - Apexcharts has its own dark/light modes

**Comment by mattwright324** [comment]
Dark mode now active!
