### ISSUE TITLE
region-restriction blocked and allowed At the same time whether the work is feasible

### ISSUE THREAD

**Issue by oplle** [mattwright324/youtube-metadata#48]
In the following example, there are 247 region blocked, and I can't immediately know which one is the allowed area
https://mattw.io/youtube-metadata/?submit=true&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DoeZG4cUw4T0

**Comment by mattwright324** [comment]
That would be a good addition, it looks like there are 249 ISO 3166 countries so there should be 2 then that are allowed. It would be useful to list the reverse of the allowed or blocked list. However, I might need to change up how to list displays so it isn't super long on the page all the time. The reverse country list could be collapsed by default then expanded if needed.

https://www.iso.org/obp/ui/#search

**Comment by mattwright324** [comment]
This is now available, the contentDetails section will now display two expandable lists: one for the provided allowed/blocked; and one for the opposite.

![image](https://user-images.githubusercontent.com/7717432/143782545-beb4dc80-fba2-455a-8255-34408bb41593.png)

I've also added a new selectable Region Restriction Count column to the Bulk section.

![image](https://user-images.githubusercontent.com/7717432/143782463-a4b8f0e6-9e1c-4f3a-9b4a-b85a35367240.png)

**Comment by mattwright324** [comment]
For that particular video example, you should now see this:
![image](https://user-images.githubusercontent.com/7717432/143782669-62f23cdb-6d31-4973-96a5-20c378077411.png)

**Comment by oplle** [comment]
Very good, thank you

**Comment by mattwright324** [comment]
Color coding is a good idea, blocked is now red and allowed is now green.

![image](https://user-images.githubusercontent.com/7717432/143788508-4e4d6328-5fe8-4c22-8a9b-aeea5dc537a6.png)

**Comment by oplle** [comment]
> Color coding is a good idea, blocked is now red and allowed is now green.
> 
> ![image](https://user-images.githubusercontent.com/7717432/143788508-4e4d6328-5fe8-4c22-8a9b-aeea5dc537a6.png)

thank you

**Comment by oplle** [comment]
Hello, I would like to ask if there is a video, Russian IP is prohibited to play, I would like to test it, because I found that the following video can only be played in Russia, but shows These 249 / 249 region(s) are not allowed to watch the video.
https://mattw.io/youtube-metadata/?submit=true&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D3NaUpZUsI9E

**Comment by mattwright324** [comment]
As far as I know there isn't a way to search by region restriction so can't really help finding videos in that situation.

Able to screenshot the Pitbull video saying its blocked? Sounds weird since there is no region restriction on that video coming back in the API.

If a video is blocked in RU and you're IP is RU but it plays, are you the channel owner? Otherwise I'd try confirming your IP location or its an issue or something else on YouTube's side.

**Comment by mattwright324** [comment]
Don't think its related to the region stuff and it is probably the case for many music/vevo channels though the Pitbull is another case of ["old channel, new channel"](https://github.com/mattwright324/youtube-metadata/wiki/YouTube-Oddities#old-channel-new-channel) as described in my oddities page.

Old (PitbullVEVO): https://www.youtube.com/channel/UCVWA4btXTFru9qM06FceSag
New (Pitbull): https://www.youtube.com/channel/UCv8nzwVPQDRjkPCkEsOdEwA

**Comment by oplle** [comment]
> As far as I know there isn't a way to search by region restriction so can't really help finding videos in that situation.
> 
> Able to screenshot the Pitbull video saying its blocked? Sounds weird since there is no region restriction on that video coming back in the API.
> 
> If a video is blocked in RU and your IP is RU but it plays, are you the channel owner? Otherwise I'd try confirming your IP location or its an issue or something else on YouTube's side.

I sent you an IP in your mailbox, and you can use this Russian IP to reproduce the questions I mentioned above
