### ISSUE TITLE
Saving webpage of results returns null

### ISSUE THREAD

**Issue by Hwurric** [mattwright324/youtube-metadata#63]
Upon saving html file of the metadata no results are showing up. This used to work until a few days ago.
[YouTube Metadata-test.html.txt](https://github.com/mattwright324/youtube-metadata/files/7731089/YouTube.Metadata-test.html.txt)

**Comment by Hwurric** [comment]
The data of interest to me (PublishedAt) is in the html code but it's not being rendered when viewed in a browser.

**Comment by mattwright324** [comment]
That isn't an intended use case but it does seem like saving the webpage as it is now does not produce a page like the example you attached.

Is there a reason you are not using the export/import functions?

**Comment by Hwurric** [comment]
I wrote a bash script to pull the published date and convert it to my timezone and then paste it into a text file using xdotool. Saving the webpage and grepping the timestamp was the fastest method. The script is working again with a tweak to the cut command (the location changed from f8 to f6).

**Comment by mattwright324** [comment]
Cool, is there no more issue then? I guess the saved webpage does still contain the content, you just can't view it in the browser as I think the project js tries to reset the page like it does when you visit it normally or clicking submit more than once.
